### ISSUE TITLE
How to view logs from newest to oldest

### ISSUE THREAD

**Issue by KVPasupuleti** [rapid7/r7insight_js#10]
In the logs data, I could see the logs with the oldest date above. I couldn't find an option to toggle this. I want to see the latest ones first.

I couldn't find anything in the [docs](https://docs.rapid7.com/insightops/getting-started) too

Is there any way we change this?

And, I don't know whether this is the right place to ask questions/doubts like this. Is there a community platform where these kinds of discussions can happen?

**Comment by sbialkowski-r7** [comment]
Hi @KVPasupuleti!

I believe that's the normal functionality in LogSearch, I'm not sure whether it's possible to toggle it to be otherwise but you can ask questions like that in the discussion forum (better place than here):
https://discuss.rapid7.com/
