### ISSUE TITLE
Support region 'us2'

### ISSUE THREAD

**Issue by vly-ginger** [rapid7/r7insight_js#11]
Our config is such that we need to use the region value of '**us2**'. Currently, the client's `validate_region` function only allows:
```
var allowed_regions = ['eu', 'us', 'ca', 'au', 'ap'];
```

Can we get support for 'us2' as a region? I temporarily modified a copy of r7insight.js to allow 'us2' and verified that the change works. However, there may be more appropriate logic (e.g. startsWith) that suits the region strategy for Rapid7 that I don't have visibility to.

**Comment by jcolgan-r7** [comment]
Hey @vly-ginger, this was added a few months ago: https://github.com/rapid7/r7insight_js/pull/8

Are you using the latest version?

**Comment by jcolgan-r7** [comment]
Let us know if you have any further problems
