### ISSUE TITLE
Can't see the logs before 30 days

### ISSUE THREAD

**Issue by KVPasupuleti** [rapid7/r7insight_js#17]
Hey team!

The range selector is so helpful to check time/period specific logs.

But when I select a range that's behind the last 30 days range, the range is getting reset to the current date and I can't see the logs the I need.

Is this expected or can we do anything on this?

**Comment by sbialkowski-r7** [comment]
Hi @KVPasupuleti, I believe this is related to the UI?

You should reach out to support with these questions, but I believe this is happening due to your retention limit being less than the range you're selecting.

You should upgrade your plan if you're looking to query more than 30 days data.
