### ISSUE TITLE
Remove IP address from log

### ISSUE THREAD

**Issue by LeanneShaw** [rapid7/r7insight_js#20]
Is there a way to prevent the ip address from appearing in the logs so that we can comply with GDPR?
We are seeing the ip address in the insightOps dashboard

**Comment by LeanneShaw** [comment]
<img width="825" alt="Screenshot 2022-07-15 at 09 05 47" src="https://user-images.githubusercontent.com/104987120/179181528-d616b4df-e00e-4775-9375-d73810d3dafb.png">

**Comment by sbialkowski-r7** [comment]
had a quick look, i don't see any functionality in this library for attaching ip address to the logline

this must be done in your code, so you should remove it from there i believe
