### ISSUE TITLE
Uncaught Error: A logger with that name already exists!

### ISSUE THREAD

**Issue by Haraldson** [rapid7/r7insight_js#22]
I’m experiencing this error in my React app, as I need to go via React lifecycle to initialize Rapid7 after fetching environment variables from my server.

I’m able to add an `initialized` property to the Rapid7 singleton, which allows me to bypass this problem; I can just destroy and reinitialize Rapid7 whenever this is needed (due to some other lifecycle -> remounting stuff going on in my app), but it feels very hacky.

```
import { useEffect, memo } from 'react'
import rapid7InsightOps from 'r7insight_js'
import { useEnvironment } from 'contexts/environment'

const Rapid7InsightOps = () => {
    const { integrations } = useEnvironment()

    useEffect(() => {
        if(!!integrations?.rapid7LogToken && !rapid7InsightOps?.initialized) {
            rapid7InsightOps?.initialized = true

            rapid7InsightOps?.init?.({
                token: integrations.rapid7LogToken,
                region: 'eu'
            })
        }

        // Destroy and ‘uninitialize’ on unmount
        return () => {
            rapid7InsightOps?.destroy?.()
            rapid7InsightOps?.initialized = false
        }
    }, [integrations?.rapid7LogToken, rapid7InsightOps?.initialized])

    return null
}
```

And yes – I could probably restructure my app, bundle the log token etc., but right now this is loaded asynchrously in order to be able to change different environment variables without having to rebuild the entire app.

---

My question is: Shouldn’t there be some kind of internal property helping me in tracking the state of the Rapid7 singleton? Throwing an error and crashing apps due to inadvertantly calling `init` once too many times feels very drastic and destructive to me, and I at least expect some help in tracking the state so that I can avoid that…

**Comment by pquinn-r7** [comment]
Hey @Haraldson,

Thanks for opening the issue.

I fully agree the behaviour of calling init multiple times being an error makes little sense and wouldn't be something I would expect as a user.

Proposed solution:

Calling init(), with the same name multiple times (init implicitly names the stream `default`) should no-op. It looks in the streams and sees it already exists, so should just return in my opinion.

Would that help your initial issue? I can put a PR in for this ASAP and we can get it released if so. Or happy to discuss more.

As for the example, I would think creating this in a useEffect without a try catch would be problematic for many libraries. Ideally a logger would be at the application level and shared. But with the above proposed change to init, the initialised state would be redundant as long as you continue to guard on waiting for the token. and destroy if the token changes (the useEffect would handle that too in your example)

**Comment by Haraldson** [comment]
@pquinn-r7 Loving the swift response time!

The proposed solution would absolutely solve this, and it would align nicely with how I‘ve come to expect this to be handled from my experience working with similar/adjacent tools, such as Bugsnag.

**Comment by pquinn-r7** [comment]
Brilliant @Haraldson. I'll get this prioritised on our side and will link any PR to this thread. Thanks for reaching out.

**Comment by Haraldson** [comment]
Thank you! Looking forward to see this change land, and thanks for the fast response and fix!

**Comment by pquinn-r7** [comment]
@Haraldson v1.1.1 has been released with the fix. Let me know if you have any issues with it.

**Comment by Haraldson** [comment]
Sweet!

As far as I understand from the little discussion in the PR, in my concrete use case, I still have to destroy and initialize again with this fix? Otherwise I'd be silently left with Rapid7 in a 'disconnected' state after a second `init()`?

(Which is totally fine, I'm just making sure before getting rid of my hack.)

**Comment by pquinn-r7** [comment]
@Haraldson so it depends. If the token and region dont change, then you dont _need_ to destroy. But if the token or region changes, then you should destroy and init a new Logger as the options will be different. 

Now if your component should clean up all traces of itself, then destroying the logger also makes sense. Its hard to tell where exactly in your app the example React component lives.

You should still be able to log to the original logger as the presence of that logger was the flag to throw the error in the init before this change. We are now just stopping processing if the logger already exists.

In the PR we were discussing if it should implicitly ignore or implicitly override. We have gone with ignore.

I hope that helps.

**Comment by Haraldson** [comment]
@pquinn-r7 Tried this out now – the NPM version’s `package.json` is pointing at `product/r7insight.js`, which still looks and works like the old version. Is it possible that you forgot running the build script?

**Comment by pquinn-r7** [comment]
@Haraldson Sorry, yeah it's a mistake on my side. Will get 1.1.2 released soon

**Comment by pquinn-r7** [comment]
Apologies for all that. There is no prepare script in the repo and completely missed that part when doing it.

v1.1.2 is released now

**Comment by Haraldson** [comment]
Works like a charm! 👌🏼
